name: Build

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  build:
    name: Build libtritonrepoagent_dragonfly.so
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          curl \
          zip \
          unzip \
          tar \
          pkg-config \
          python3

      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
          $HOME/vcpkg/bootstrap-vcpkg.sh

      - name: Install project dependencies with vcpkg
        run: |
          $HOME/vcpkg/vcpkg install re2
          $HOME/vcpkg/vcpkg install aws-sdk-cpp
          $HOME/vcpkg/vcpkg install google-cloud-cpp[storage]
          $HOME/vcpkg/vcpkg install azure-storage-blobs-cpp
          $HOME/vcpkg/vcpkg install rapidjson

      - name: Create build directory
        run: mkdir -p $HOME/build

      - name: Build the repository agent
        run: |
          mkdir -p $HOME/build && cd $HOME/build
          cmake -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
                -DTRITON_ENABLE_GCS=true \
                -DTRITON_ENABLE_AZURE_STORAGE=true \
                -DTRITON_ENABLE_S3=true \
                -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
                $GITHUB_WORKSPACE
          make install
